/* Generated by scripts/pull-races.mjs — do not edit by hand.
   Refresh with `npm run seo:races` against a running backend. */

/**
 * The race catalogue, as the build needs to know it.
 *
 * **Committed on purpose, for the same reason `openapi/openapi.json` is.** A
 * static export has to know every page's address before it runs, and the only
 * live source of the race list is the backend — so generating these pages from
 * the API at build time would make every deploy depend on the API being up,
 * and a deploy during an outage would silently ship a site with no races in it.
 *
 * This is why course pages used to be addressed as `?course=<slug>`: one page,
 * nine races, and nothing a search engine could tell apart. Committing the list
 * answers that objection without taking on the dependency — the data changes a
 * few times a season, it is public information already on the race directory,
 * and `npm run seo:races` refreshes it in one command.
 *
 * Only what a *signed-out* visitor may see is here. Nothing behind the paywall
 * — no geometry, no elevation series, no cut-off ladder — appears in a
 * prerendered page, because prerendered means public.
 */
export type SeoRace = {
  slug: string;
  name: string;
  /** "Calella, Spain" — as shown in the directory. */
  place: string;
  /** ISO 3166-1 alpha-2, for structured data. */
  country: string;
  /** "Full" | "70.3" | "Olympic" | "Sprint". */
  distance: string;
  difficulty: string;
  lat: number;
  lng: number;
  /** ISO date, or null for the showcase course which is not an event. */
  date: string | null;
  available: boolean;
  /** The signed-out marketing map; listed, but not a race anyone enters. */
  showcase: boolean;
};

export const SEO_RACES: readonly SeoRace[] = [
  {
    slug: "calella-barcelona-full",
    name: "IRONMAN Calella-Barcelona",
    place: "Calella, Spain",
    country: "ES",
    distance: "Full",
    difficulty: "MODERATE",
    lat: 41.6146,
    lng: 2.6544,
    date: "2026-10-04",
    available: true,
    showcase: false,
  },
  {
    slug: "versailles-703",
    name: "IRONMAN 70.3 Versailles",
    place: "Versailles, France",
    country: "FR",
    distance: "70.3",
    difficulty: "MODERATE",
    lat: 48.8049,
    lng: 2.1204,
    date: "2026-10-11",
    available: true,
    showcase: false,
  },
  {
    slug: "portugal-cascais-703",
    name: "IRONMAN 70.3 Portugal-Cascais",
    place: "Cascais, Portugal",
    country: "PT",
    distance: "70.3",
    difficulty: "MODERATE",
    lat: 38.6979,
    lng: -9.4215,
    date: "2026-10-17",
    available: true,
    showcase: false,
  },
  {
    slug: "portugal-cascais-full",
    name: "IRONMAN Portugal-Cascais",
    place: "Cascais, Portugal",
    country: "PT",
    distance: "Full",
    difficulty: "HARD",
    lat: 38.6979,
    lng: -9.4215,
    date: "2026-10-17",
    available: true,
    showcase: false,
  },
  {
    slug: "malaga-703",
    name: "IRONMAN 70.3 Málaga",
    place: "Málaga, Spain",
    country: "ES",
    distance: "70.3",
    difficulty: "HARD",
    lat: 36.7213,
    lng: -4.4214,
    date: "2026-10-18",
    available: true,
    showcase: false,
  },
  {
    slug: "porec-703",
    name: "IRONMAN 70.3 Poreč",
    place: "Poreč, Croatia",
    country: "HR",
    distance: "70.3",
    difficulty: "MODERATE",
    lat: 45.227,
    lng: 13.594,
    date: "2026-10-18",
    available: true,
    showcase: false,
  },
  {
    slug: "costa-navarino-703",
    name: "IRONMAN 70.3 Costa Navarino, Peloponnese, Greece",
    place: "Peloponnese, Greece",
    country: "GR",
    distance: "70.3",
    difficulty: "MODERATE",
    lat: 36.9636,
    lng: 21.6553,
    date: "2026-10-25",
    available: true,
    showcase: false,
  },
  {
    slug: "turkiye-703",
    name: "IRONMAN 70.3 Türkiye",
    place: "Antalya, Türkiye",
    country: "TR",
    distance: "70.3",
    difficulty: "APPROACHABLE",
    lat: 36.863,
    lng: 31.056,
    date: "2026-11-01",
    available: true,
    showcase: false,
  },
  {
    slug: "kalmar-703",
    name: "Kalmar 70.3",
    place: "Kalmar, Sweden",
    country: "SE",
    distance: "70.3",
    difficulty: "APPROACHABLE",
    lat: 56.657,
    lng: 16.362,
    date: null,
    available: true,
    showcase: true,
  },
] as const;

/** The races that get their own indexable page: real events, not the showcase. */
export const INDEXABLE_RACES: readonly SeoRace[] = SEO_RACES.filter(
  (race) => !race.showcase,
);

export function raceBySlug(slug: string): SeoRace | undefined {
  return SEO_RACES.find((race) => race.slug === slug);
}

/** "70.3" reads as a distance to a human; "Full" needs saying properly. */
export function distanceLabel(distance: string): string {
  return distance === "Full" ? "Full distance" : distance;
}

/** "4 October 2026", or null for the showcase. */
export function raceDateLabel(date: string | null): string | null {
  if (!date) return null;
  return new Date(`${date}T00:00:00Z`).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}
