/* Generated by scripts/asset-manifest.mjs — do not edit.
   Regenerated on every build (see the `prebuild` script), so it cannot
   drift from what is on disk. */

export const ASSET_FILES: ReadonlySet<string> = new Set([
  "assets/account/elena.webp",
  "assets/account/jonas.webp",
  "assets/athletes/aiko.webp",
  "assets/athletes/dan.webp",
  "assets/athletes/ines.webp",
  "assets/athletes/jonas.webp",
  "assets/athletes/karl.webp",
  "assets/athletes/lena.webp",
  "assets/athletes/marcus.webp",
  "assets/athletes/maya.webp",
  "assets/athletes/priya.webp",
  "assets/athletes/rui.webp",
  "assets/athletes/sofia.webp",
  "assets/athletes/tom.webp",
  "assets/auth/dawn-transition.webp",
  "assets/authors/jonas.webp",
  "assets/bags/bike-sn.webp",
  "assets/bags/bike-t1.webp",
  "assets/bags/morning.webp",
  "assets/bags/run-sn.webp",
  "assets/bags/run-t2.webp",
  "assets/coach/feldt-mark.webp",
  "assets/courses/belgrade-703.webp",
  "assets/courses/ironman-wales.webp",
  "assets/courses/italy-emilia-romagna-703.webp",
  "assets/courses/italy-emilia-romagna-full.webp",
  "assets/courses/kalmar-703.webp",
  "assets/courses/malaga-703.webp",
  "assets/courses/nice-703-world-championship.webp",
  "assets/courses/porec-703.webp",
  "assets/courses/portugal-cascais-703.webp",
  "assets/courses/portugal-cascais-full.webp",
  "assets/cta/dawn-swim.webp",
  "assets/dashboard/post-race.webp",
  "assets/guide/valley-drag.webp",
  "assets/hero/hero-loop.mp4",
  "assets/hero/hero-loop.webm",
  "assets/how/dawn-start.webp",
  "assets/how/solver-desk.webp",
  "assets/plan/review-locked.webp",
  "assets/system/lost-road.webp",
]);

/** Whether a file is actually present, so nothing asks the network blindly. */
export function assetExists(path: string | null | undefined): boolean {
  return !!path && ASSET_FILES.has(path.replace(/^\/+/, ""));
}
