/** Central route map so every page's nav/footer links point at the same real paths. */
export const routes = {
  home: "/",
  races: "/races",
  howItWorks: "/how-it-works",
  pricing: "/pricing",
  dashboard: "/dashboard",
  myPlans: "/plans",
  courseRecon: "/course-recon",
  racePlan: "/plan",
  planBuilder: "/plan-builder",
  checkout: "/checkout",
  login: "/login",
  signup: "/signup",
  resetPassword: "/reset-password",
  onboarding: "/onboarding",
  raceMode: "/race-mode",
  postRace: "/post-race",
  settings: "/settings",
  notifications: "/notifications",
  coach: "/coach",
  admin: "/admin",
  guide: "/guide",
  sharedPlan: "/shared",
  systemStates: "/system-states",
} as const;
