#!/usr/bin/env node
/**
 * Refresh `lib/seo/races.ts` from a running backend.
 *
 * The race list has to be known before the build runs, because a static export
 * writes one HTML file per address and the addresses include one page per race.
 * Fetching it *during* the build would make every deploy depend on the API
 * being up, and a deploy during an outage would quietly ship a site with no
 * races in it. So the list is committed, exactly as `openapi/openapi.json` is,
 * and this script is how it gets updated — deliberately, by a person, with the
 * diff visible in the commit.
 *
 * Run it whenever the race catalogue changes: a race added, removed, renamed,
 * or its date moved. `docs/SEO.md` says which changes need it.
 *
 *   npm run seo:races                       # against the default API
 *   API=https://api.example.com npm run seo:races
 */

import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "lib", "seo", "races.ts");

const api = (process.env.API || process.env.NEXT_PUBLIC_API_BASE_URL || "")
  .trim()
  .replace(/\/+$/, "");
if (!api) {
  console.error(
    "pull-races: no API origin.\n" +
      "Set API or NEXT_PUBLIC_API_BASE_URL, e.g.\n" +
      "  API=https://race-os-backend.onrender.com npm run seo:races",
  );
  process.exit(1);
}

/* Signed out on purpose. This file feeds prerendered pages, and prerendered
   means public — so it must contain exactly what a visitor with no account is
   allowed to see, which is what the anonymous directory returns. */
const response = await fetch(`${api}/api/v1/courses`, {
  headers: { Accept: "application/json" },
}).catch((error) => {
  console.error(`pull-races: could not reach ${api} — ${error.message}`);
  process.exit(1);
});

if (!response.ok) {
  console.error(`pull-races: ${api} answered ${response.status}`);
  process.exit(1);
}

const body = await response.json();
const rows = Array.isArray(body?.data) ? body.data : [];
if (rows.length === 0) {
  // Overwriting the committed list with nothing would remove every race page
  // and hand Google a sitemap that had lost most of its URLs.
  console.error("pull-races: the directory came back empty; refusing to write");
  process.exit(1);
}

const races = rows
  .map((row) => ({
    slug: String(row.slug),
    name: String(row.official_event_name || row.name),
    place: String(row.place),
    country: countryOf(row.timezone, row.place),
    distance: String(row.distance_type),
    difficulty: String(row.difficulty),
    lat: Number(row.lat),
    lng: Number(row.lng),
    date: row.next_edition_date ?? null,
    available: row.availability === "available",
    showcase: row.visibility === "showcase",
  }))
  .sort(byDateThenName);

/** The API does not return a country code, and structured data wants one. */
function countryOf(timezone, place) {
  const byZone = {
    "Europe/Madrid": "ES",
    "Europe/Paris": "FR",
    "Europe/Lisbon": "PT",
    "Europe/Zagreb": "HR",
    "Europe/Athens": "GR",
    "Europe/Istanbul": "TR",
    "Europe/Stockholm": "SE",
    "Europe/Rome": "IT",
    "Europe/Berlin": "DE",
    "Europe/London": "GB",
    "Europe/Belgrade": "RS",
  };
  const code = byZone[timezone];
  if (code) return code;
  console.warn(
    `pull-races: no country code for timezone ${timezone} (${place}); ` +
      `add it to countryOf() in this script`,
  );
  return "";
}

/** Same order the directory uses, so a diff reads as a season, not a shuffle. */
function byDateThenName(a, b) {
  if (a.date && b.date && a.date !== b.date) return a.date < b.date ? -1 : 1;
  if (a.date && !b.date) return -1;
  if (!a.date && b.date) return 1;
  return a.name.localeCompare(b.name);
}

const fields = [
  "slug",
  "name",
  "place",
  "country",
  "distance",
  "difficulty",
  "lat",
  "lng",
  "date",
  "available",
  "showcase",
];

const literal = races
  .map(
    (race) =>
      "  {\n" +
      fields.map((key) => `    ${key}: ${JSON.stringify(race[key])},`).join("\n") +
      "\n  },",
  )
  .join("\n");

const file = `/* Generated by scripts/pull-races.mjs — do not edit by hand.
   Refresh with \`npm run seo:races\` against a running backend. */

/**
 * The race catalogue, as the build needs to know it.
 *
 * **Committed on purpose, for the same reason \`openapi/openapi.json\` is.** A
 * static export has to know every page's address before it runs, and the only
 * live source of the race list is the backend — so generating these pages from
 * the API at build time would make every deploy depend on the API being up,
 * and a deploy during an outage would silently ship a site with no races in it.
 *
 * This is why course pages used to be addressed as \`?course=<slug>\`: one page,
 * nine races, and nothing a search engine could tell apart. Committing the list
 * answers that objection without taking on the dependency — the data changes a
 * few times a season, it is public information already on the race directory,
 * and \`npm run seo:races\` refreshes it in one command.
 *
 * Only what a *signed-out* visitor may see is here. Nothing behind the paywall
 * — no geometry, no elevation series, no cut-off ladder — appears in a
 * prerendered page, because prerendered means public.
 */
export type SeoRace = {
  slug: string;
  /** "Calella, Spain" — as shown in the directory. */
  name: string;
  place: string;
  /** ISO 3166-1 alpha-2, for structured data. */
  country: string;
  /** "Full" | "70.3" | "Olympic" | "Sprint". */
  distance: string;
  difficulty: string;
  lat: number;
  lng: number;
  /** ISO date, or null for the showcase course which is not an event. */
  date: string | null;
  available: boolean;
  /** The signed-out marketing map; listed, but not a race anyone enters. */
  showcase: boolean;
};

export const SEO_RACES: readonly SeoRace[] = [
${literal}
] as const;

/** The races that get their own indexable page: real events, not the showcase. */
export const INDEXABLE_RACES: readonly SeoRace[] = SEO_RACES.filter(
  (race) => !race.showcase,
);

export function raceBySlug(slug: string): SeoRace | undefined {
  return SEO_RACES.find((race) => race.slug === slug);
}

/** "70.3" reads as a distance to a human; "Full" needs saying properly. */
export function distanceLabel(distance: string): string {
  return distance === "Full" ? "Full distance" : distance;
}

/** "4 October 2026", or null for the showcase. */
export function raceDateLabel(date: string | null): string | null {
  if (!date) return null;
  return new Date(\`\${date}T00:00:00Z\`).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}
`;

await writeFile(OUT, file, "utf8");
console.log(
  `pull-races: wrote ${races.length} races (${races.filter((r) => !r.showcase).length} indexable) from ${api}`,
);
