#!/usr/bin/env node
/**
 * Write `public/_headers`, which Cloudflare Pages applies to every response.
 *
 * A static export cannot set headers from `next.config.ts` — there is no
 * server in the request path to set them — so `headers()` there does nothing
 * and the site shipped with none at all. That left the app that handles
 * sign-in and payment framable by any origin and with no content-security
 * policy behind its one `dangerouslySetInnerHTML`.
 *
 * The policy is generated rather than written by hand because `connect-src`
 * has to name the API exactly, and the API origin is a build-time variable.
 * Hardcoding it would be wrong in every environment but one, and widening it
 * to `https:` would let injected script exfiltrate to anywhere, which is most
 * of what a CSP is for.
 *
 * Regenerated by `prebuild`, so it cannot drift from the build it describes.
 */

import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadEnv } from "./load-env.mjs";

/* `next build` reads .env.local itself; this script runs before it and would
   otherwise see only the real environment. */
const envFiles = loadEnv();

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "_headers");

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
let apiOrigin = "";
try {
  apiOrigin = apiBase ? new URL(apiBase).origin : "";
} catch {
  apiOrigin = "";
}
if (!apiOrigin) {
  // Failing the build beats shipping a policy that blocks every API call, or
  // one so wide it protects nothing.
  console.error(
    "security-headers: NEXT_PUBLIC_API_BASE_URL is missing or not a URL.\n" +
      "It is required to write connect-src.\n\n" +
      "Set it for the build:\n" +
      "  NEXT_PUBLIC_API_BASE_URL=https://your-api.example npm run build\n" +
      "or put it in .env.local (copy .env.example), which is now read here too.\n" +
      (envFiles.length
        ? `Read ${envFiles.join(", ")}, and it was not in there.`
        : "No .env.local or .env was found in the project root."),
  );
  process.exit(1);
}

/* Stripe is listed although nothing loads it yet: `@stripe/stripe-js` is a
   dependency and card confirmation is the next thing to be wired. Allowing an
   origin that is not used costs nothing; discovering the policy blocks
   checkout does, and it would be discovered in production. */
const STRIPE = "https://js.stripe.com";

const csp = [
  "default-src 'none'",
  // Next.js inlines a small bootstrap and its route manifest.
  `script-src 'self' 'unsafe-inline' ${STRIPE}`,
  // Styles are inlined per component throughout this app.
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://api.fontshare.com",
  "font-src 'self' https://fonts.gstatic.com https://api.fontshare.com data:",
  "img-src 'self' data: blob:",
  "media-src 'self'",
  `connect-src 'self' ${apiOrigin}`,
  `frame-src ${STRIPE}`,
  "worker-src 'self'",
  "manifest-src 'self'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

const headers = `# Generated by scripts/security-headers.mjs — do not edit.
# Regenerated on every build (see the \`prebuild\` script).
#
# Cloudflare Pages reads this file from the output root. A static export has
# no server to set headers, so this is the only place they can come from.

/*
  Content-Security-Policy: ${csp}
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), usb=(), interest-cohort=(), payment=(self "${STRIPE}")
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Cross-Origin-Opener-Policy: same-origin
  X-DNS-Prefetch-Control: off

# Hashed filenames: safe to cache hard, and a stale one is never served
# because the name changes with the content.
/_next/static/*
  Cache-Control: public, max-age=31536000, immutable

# The service worker must not be cached, or a release cannot replace it.
/sw.js
  Cache-Control: no-cache
`;

await writeFile(OUT, headers, "utf8");
console.log(`security headers: connect-src ${apiOrigin}`);
